# Generated by Django 4.2.6 on 2023-10-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student Management System', 'verbose_name_plural': "Student Management System'"},
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Contact',
            new_name='Age',
        ),
        migrations.AddField(
            model_name='student',
            name='Subject',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='student',
            table='',
        ),
    ]
